### ISSUE TITLE
[BUG] Fix compatibility with build 1101 (Identity Update)

### ISSUE THREAD

**Issue by forever-and-a-day** [FelkonEx/FavCat-Restored#1]
Recent vrchat identity update has broken FavCat Restored. Upstream FavCat is fixed as of now.

**Comment by JoeyDagger** [comment]
https://github.com/knah/VRCMods/commit/3557896902165980e1ba978a9adda09044481d48
For easier access to fix.

**Comment by FelkonEXE** [comment]
Looks like It's only UIX changes. Working on getting a stable version of an earlier build with those UIX Changes at the moment as an interim before i continue with the upstream pushes.

**Comment by FelkonEXE** [comment]
~~Fixed here: https://github.com/FelkonEx/FavCat-Restored/releases/tag/1.1.1~~
EDIT: See below comment

**Comment by FelkonEXE** [comment]
Fixed for most recent version (1102) here: https://github.com/FelkonEx/FavCat-Restored/releases/tag/1.1.4
