### ISSUE TITLE
[VRChat UPDATE] Add forward compatibility with build 1118 (Unity 2019 Update)

### ISSUE THREAD

**Issue by forever-and-a-day** [FelkonEx/FavCat-Restored#13]
### **VRChat version to update to:** 1118
Changes have been made upstream in FavCat, they just need to be ported over to FavCat Restored.

**Comment by FelkonEXE** [comment]
I'll give it a look, been AWOL from VR chat for a hot minute.
Also always open to look at PR's if you ever wanted to try implementing the upstream changes yourself

**Comment by FelkonEXE** [comment]
Changes done here: https://github.com/FelkonEx/FavCat-Restored/releases/tag/1.1.6
