### ISSUE TITLE
Import from text files [BUG] 

### ISSUE THREAD

**Issue by vampiricwulf** [FelkonEx/FavCat-Restored#16]
### **Describe the bug**
Clicking "Import datases and text files" does nothing.

### **Questions:**
 - Which version of VRChat are you running?: Latest 
 - Are you using the latest version of FavCatRestored?:Yes
 - Are you using the latest version of UIX?: Yes
 - Does the issue happen if you only use FavCatRestored & UIX? Not Tested
 - Are you using the latest version of melonloader / emmVRC?: Yes

### **Additional context**
I was testing importing avatars by first adding random ones and exporting that, moving the file over to the import folder, removing my favorites, and then importing. Nothing appears.

**Comment by FelkonEXE** [comment]
Hmm, that's a strange one. I haven't personally tried doing any importing data from text files, but I'll have a look and see what's up
