### ISSUE TITLE
[FEATURE REQUEST] Port online/offline status for user favorites 

### ISSUE THREAD

**Issue by forever-and-a-day** [FelkonEx/FavCat-Restored#2]
Upstream favcat now shows online/offline status on user favorites. Would be nice to have this fix ported to Favcat Restored!

**Comment by FelkonEXE** [comment]
I'll slowly be going through changes upstream over the next couple of days / week.
Hard Drive's died on me recently, so I've been away for the last couple weeks.

**Comment by JoeyDagger** [comment]
Completely understandable. Take your time.

**Comment by ghost** [comment]
https://github.com/xAstroBoy/VRCMods-Unlocked/

Done.

**Comment by FelkonEXE** [comment]
Welp, finally got around to fixing it:
https://github.com/FelkonEx/FavCat-Restored/releases/tag/1.1.5
Updated for most ML 4.0 & VRC Version 1108
