### ISSUE TITLE
[BUG] No longer works on Build 1149 (VRChat UI 1.5 Update)

### ISSUE THREAD

**Issue by forever-and-a-day** [FelkonEx/FavCat-Restored#20]
### **Describe the bug**
FavCat Restored does not work at all on this version. Changes appear to be made to upstream FavCat to help with this issue, but I'm not knowledgeable enough in C# to help port them :( 
Note that UIX has also been updated to support this update, however it will not load correctly with the current VRCMG-approved version of PortableMirrorMod. If you use this mod, remove it or update it from it's gh repo. Just a heads up. 

### **Screenshots**
Not applicable in this case.

### **Questions:**
 - Which version of VRChat are you running?: 
Build 1149
 - Are you using the latest version of FavCatRestored?:
Yes. 
 - Are you using the latest version of UIX?: 
Yes. 
 - Does the issue happen if you only use FavCatRestored & UIX?
Yes. 
 - Are you using the latest version of melonloader / emmVRC?:
Yes (new loader). 

### **Additional context**
Relevant upstream commit: https://github.com/knah/VRCMods/commit/143be95967696001b870b1f43659aabc6abc99e8

**Comment by FelkonEXE** [comment]
Just released 1.1.9, should work with 1149.

https://github.com/FelkonEx/FavCat-Restored/releases/tag/1.1.9
