### ISSUE TITLE
[Bug Report] Can't create new categories

### ISSUE THREAD

**Issue by Mskitty301** [FelkonEx/FavCat-Restored#7]
Can't change categories either like renaming them and stuff.

**Comment by FelkonEXE** [comment]
I've gone and tested with the most recent versions of [FavCatRestored](https://github.com/FelkonEx/FavCat-Restored/releases/tag/1.1.4), and [UIX](https://github.com/knah/VRCMods/releases/tag/updates-2021-06-02-2); and it looks like i can still create, rename, and everything else with the categories.

Do the following for me:
- Check to make sure if UIX and FavCatRestored are the most recent versions
- Check if the issue occurs with only UIX & FavCatRestored as the only 2 mods installed

**Comment by Mskitty301** [comment]
I tried it again and it just suddenly worked for me. I think my uix wasn't updated at the time or it was just a random bug.

fav cat v1.1.4
uix v0.3.2
