### ISSUE TITLE
[BUG] MelonLoader v0.4.0 Update

### ISSUE THREAD

**Issue by JoeyDagger** [FelkonEx/FavCat-Restored#8]
MelonLoader Updated to v0.4.0. Not entirely sure if it requires an update, but I would assume so since mods mods need to. 

Here's the info:
![image](https://user-images.githubusercontent.com/67937427/122332454-47130f80-ceeb-11eb-8cf8-216f0df2174b.png)

**Comment by xAstroBoy** [comment]
Don already <3

**Comment by forever-and-a-day** [comment]
> Don already <3

@xAstroBoy u thinking of doing pull requests in this repo? Would prob be helpful, I'm sure Felkon would accept.

**Comment by JoeyDagger** [comment]
Ok yeah it works I'm a goof

**Comment by FelkonEx** [comment]
@JoeyDagger FYI the newest version should work with ML 0.4.0 and the most recent version of UIX
