### ISSUE TITLE
[BUG] No longer able to add or select worlds in the categorized favorites 

### ISSUE THREAD

**Issue by Kotogoi** [FelkonEx/FavCat-Restored#9]
### **Describe the bug**
The same bug happened during the update before the last. The avatar favs work with no issues, however, the world favs are no longer able to be used. They are still there in the categories that I organized them in and are able to be added, but are not able to be selected.

### **Questions:**
 - Which version of VRChat are you running?: Latest
 - Are you using the latest version of FavCatRestored?: Release 1.1.4
 - Are you using the latest version of UIX?: Latest
 - Does the issue happen if you only use FavCatRestored & UIX?: Only happens with favcat
 - Are you using the latest version of melonloader / emmVRC?: Melon loader 4.0 and the latest emmvrc release

**Comment by FelkonEXE** [comment]
Yep, working on this! 
Will be upstreaming all the changes as well for the most recent versions 👍

**Comment by FelkonEXE** [comment]
Fixed here:
https://github.com/FelkonEx/FavCat-Restored/releases/tag/1.1.5
